version: '3.7'
#https://hub.docker.com/_/joomla/
services:
  web:
    image: xoroz.com/joomla-web
#    image: xoroz/joomla-web
    ports:
      - "${SITE_PORT}:80"
    volumes:
      - joomla_web:/var/www
    environment:
      - JOOMLA_DB_HOST=db
      - JOOMLA_DB_PASSWORD=${DB_ROOT_PASSWORD}
    depends_on:
      - db
    deploy:
      resources:
        limits:
         cpus: '0.50'
         memory: 128M
        reservations:
         cpus: '0.10'
         memory: 20M
      replicas: 1
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
  db:
    image: xoroz.com/pk-db:latest
#    image: xoroz/pk-db:latest

    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=$DB_ROOT_PASSWORD
    volumes:
      - joomla_db:/bitnami/mariadb/data


volumes:
 joomla_web:
  name: ${SITE_VOLUME}
  external: false
 joomla_db:
  name: ${DB_VOLUME}
  external: false

